function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.released then
		if gui.pick_node(gui.get_node("playgamebutton"), action.x, action.y) then
			msg.post("loader:/controller", "show_game")
		elseif gui.pick_node(gui.get_node("quitgamebutton"), action.x, action.y) then
			msg.post("loader:/controller", "quit_game")
		end
	end
end
